# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


format = """
$username\
$all\
$time\
$character\
"""

command_timeout = 1000

[shell]
# bash_indicator = 'ó±†ƒ'
bash_indicator = '#!'
fish_indicator = 'ó°ˆº'
# powershell_indicator = 'ï‘ _'
# powershell_indicator = 'âš¡'
powershell_indicator = 'ïƒ§'
zsh_indicator = 'âš¡sh'
# command_prompt_indicator = 'ó°¨¡ ' ??
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false
format='[$indicator]($style) '


# [battery]
# full_symbol = 'ğŸ”‹ '
# charging_symbol = 'âš¡ï¸ '
# discharging_symbol = 'ğŸ’€ '
# disabled = false

# [[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
# threshold = 10
# style = 'bold red'

# [[battery.display]] # 'bold yellow' style and ğŸ’¦ symbol when capacity is between 10% and 30%
# threshold = 30
# style = 'bold yellow'
# discharging_symbol = 'ğŸ’¦'

# [[battery.display]] # 'bold yellow' style and ğŸ’¦ symbol when capacity is between 10% and 30%
# threshold = 100
# style = 'bold green'



[cmd_duration]
min_time = 500
# format = 'underwent [$duration](bold yellow)'


[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

[username]
format = '[$user]($style) '

[hostname]
# ssh_only = false
# disabled = true
format = '[$ssh_symbol](bold blue)[$hostname](fg:#72de3e) in'
# format = '[$ssh_symbol](bold blue)[$hostname](fg:green) '

[conda]
symbol = 'ğŸ'
# format = '[$symbol $environment](green) '

[directory]
truncation_length = 2
truncation_symbol = 'â€¦/'
truncate_to_repo = false
# style = '#50e6ff'
format = 'in [$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 19
# truncation_symbol = ''
# ignore_branches = ['master', 'main']

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_metrics]
# added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[git_status]
conflicted = 'ğŸ³'
# ahead = 'ğŸğŸ’¨'
# behind = 'ğŸ˜°'
# diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
# deleted = 'ğŸ—‘'
deleted = 'ï’'
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[time]
disabled = false
format = 'at ğŸ•™[\[ $time \]]($style) '
style = "bg:#1d2230"
time_format = '%T'
utc_time_offset = '+5.5'
# time_range = '10:00:00-14:00:00'

# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#1d2230"
# format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'

# [time]
# disabled = false
# utc_time_offset = '+5.30'
# format = '\[[$time]($style)\]'

